### PR TITLE
Support Node v12

### PR DESCRIPTION
**Pull request by javiergarmon**

### CODE REVIEW

**Comment by bbondy** [comment]
Does this still compile with Node v10 too?
If not it'd be best to support both maybe with `#if defined`

**Comment by javiergarmon** [comment]
@bbondy yes! This compiles and works with Node.js v10 too!

**Review by bbondy — APPROVED** [review]

**Comment by javiergarmon** [comment]
@bbondy Maybe it's a good idea to release a new version of the package, don't you think?

**Comment by bbondy** [comment]
👍 done

**Comment by bbondy** [comment]
bloom-filter-cpp@1.2.2

**Comment by javiergarmon** [comment]
Thanks man!

**Comment by sannysoft** [comment]
@javiergarmon Can you fix it for Node v.14 as well please? :)

**Comment by bbondy** [comment]
Sorry this is no longer maintained

**Pull request merged**
