### PR TITLE
Fix build failure on Node v10 (fixes #4)

### LINKED ISSUE #4: Build fails on Node v10
```cxx
  CXX(target) Release/obj.target/bloom-filter-cpp/addon.o
  CXX(target) Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o
../BloomFilterWrap.cpp: In static member function ‘static void BloomFilterWrap::BloomFilterWrap::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../BloomFilterWrap.cpp:62:59: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [1])’
     args.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                           ^
In file included from ~/.node-gyp/10.0.0/include/node/node.h:63:0,
                 from ../BloomFilterWrap.h:9,
                 from ../BloomFilterWrap.cpp:6:
~/.node-gyp/10.0.0/include/node/v8.h:3848:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
~/.node-gyp/10.0.0/include/node/v8.h:3848:44: note:   candidate expects 3 arguments, 2 provided
~/.node-gyp/10.0.0/include/node/v8.h:3851:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
~/.node-gyp/10.0.0/include/node/v8.h:3851:44: note:   candidate expects 1 argument, 2 provided
../BloomFilterWrap.cpp: In static member function ‘static void BloomFilterWrap::BloomFilterWrap::Add(const v8::FunctionCallbackInfo<v8::Value>&)’:
../BloomFilterWrap.cpp:67:44: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value str(args[0]->ToString());
                                            ^
In file included from ~/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from ~/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../BloomFilterWrap.h:9,
                 from ../BloomFilterWrap.cpp:6:
~/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
~/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../BloomFilterWrap.cpp: In static member function ‘static void BloomFilterWrap::BloomFilterWrap::Exists(const v8::FunctionCallbackInfo<v8::Value>&)’:
../BloomFilterWrap.cpp:76:44: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value str(args[0]->ToString());
                                            ^
In file included from ~/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from ~/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../BloomFilterWrap.h:9,
                 from ../BloomFilterWrap.cpp:6:
~/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
~/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
bloom-filter-cpp.target.mk:100: recipe for target 'Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o' failed
make: *** [Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o] Error 1
```

### PR DESCRIPTION
**Pull request by davidar**

### CODE REVIEW

**Comment by pfrazee** [comment]
@bbondy can this be merged?

**Review by bbondy — APPROVED** [review]

**Comment by bbondy** [comment]
done

**Comment by pfrazee** [comment]
Thanks!

**Comment by pfrazee** [comment]
@bbondy can you publish this on NPM?

**Comment by bbondy** [comment]
bloom-filter-cpp@1.1.8

**Pull request merged**
